#!/usr/bin/env python3
import sys

path = r'C:\Users\csbd\.openclaw\workspace\e-commerce-tools\skills\amazon-listing-doctor\diagnose.js'
with open(path, 'rb') as f:
    data = f.read()

CRLF = b'\r\n'

# step7 search target - the ORIGINAL content (not yet patched)
old7 = (
    CRLF + b"  // No competitor pool needed \xe2\x80\x94 all segments now come from self + E-GEO data" + CRLF +
    CRLF + b"  var CAPACITY_SIGNALS = /\\d+\\s*(lbs?|kg|oz|pcs?|piece|set|gal|hour|min|inch|cm|mm|ft)/i;"
)

new7 = (
    CRLF + b"  // \xe2\x80\x94 LLM-driven title generation (step7) \xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94" + CRLF +
    b"  var stepLLM = require('./stepLLM');" + CRLF +
    b"  var s11 = ctx.deps[11] ? ctx.deps[11].data : null;" + CRLF +
    b"  var violations = (s11 ? (s11.violations || []) : []).filter(function(v) { return v.severity && v.severity !== 'none'; });" + CRLF +
    b"  var s5primary = (s5.primary || []).map(function(k) { return typeof k === 'string' ? k : (k.keyword || ''); }).filter(function(k) { return k; });" + CRLF +
    b"  log('  [step7] generating optimized titles via LLM...');" + CRLF +
    b"  var llmTitles = null;" + CRLF +
    b"  try {" + CRLF +
    b"    llmTitles = await stepLLM.generateOptimizedTitles({" + CRLF +
    b"      title: s2.title || ''," + CRLF +
    b"      brand: brand," + CRLF +
    b"      coreProduct: coreProduct," + CRLF +
    b"      primaryKeywords: s5primary," + CRLF +
    b"      violations: violations" + CRLF +
    b"    });" + CRLF +
    b"  } catch(e) {" + CRLF +
    b"    log('  [step7] LLM title gen failed: ' + e.message + ' \xe2\x80\x94 falling back to rule engine');" + CRLF +
    b"  }" + CRLF +
    b"  var versionA, versionB, versionC, recommendation;" + CRLF +
    b"  if (llmTitles && llmTitles.versionA && llmTitles.versionA.text) {" + CRLF +
    b"    versionA = llmTitles.versionA.text.substring(0, 200);" + CRLF +
    b"    versionB = llmTitles.versionB && llmTitles.versionB.text ? llmTitles.versionB.text.substring(0, 200) : versionA;" + CRLF +
    b"    versionC = llmTitles.versionC && llmTitles.versionC.text ? llmTitles.versionC.text.substring(0, 200) : versionB;" + CRLF +
    b"    recommendation = (llmTitles.versionA.note || 'Generated by LLM.') + ' Original char count: ' + (s2.title || '').length + '.';" + CRLF +
    b"    return {" + CRLF +
    b"      versionA: versionA," + CRLF +
    b"      versionB: versionB," + CRLF +
    b"      versionC: versionC," + CRLF +
    b"      topSegments: []," + CRLF +
    b"      recommendation: recommendation" + CRLF +
    b"    };" + CRLF +
    b"  }" + CRLF +
    b"  // Fallback: Rule-based title generation" + CRLF +
    b"  var CAPACITY_SIGNALS = /\\d+\\s*(lbs?|kg|oz|pcs?|piece|set|gal|hour|min|inch|cm|mm|ft)/i;"
)

idx7 = data.find(old7)
if idx7 < 0:
    print('step7 NOT FOUND')
    # Debug: find the No competitor pool comment
    nc = b'No competitor pool needed'
    ncidx = data.find(nc)
    print('  No competitor pool at byte', ncidx)
    print('  context:', repr(data[ncidx:ncidx+100]))
    sys.exit(1)

print('step7 found at byte', idx7)
data = data[:idx7] + new7 + data[idx7+len(old7):]
with open(path, 'wb') as f:
    f.write(data)
print('step7 patched OK, new size:', len(data))
