#!/usr/bin/env python3
import sys, os, re

path = r'C:\Users\csbd\.openclaw\workspace\e-commerce-tools\skills\amazon-listing-doctor\diagnose.js'
with open(path, 'rb') as f:
    data = f.read()

LF = b'\n'
CRLF = b'\r\n'

# ── PATCH 1: step7 — insert LLM title generation before rule engine ──
old7 = CRLF + b'  // No competitor pool needed \xe2\x80\x94 all segments now come from self + E-GEO data' + CRLF + CRLF + b'  var CAPACITY_SIGNALS = /\\d+\\s*(lbs?|kg|oz|pcs?|piece|set|gal|hour|min|inch|cm|mm|ft)/i;'
new7 = (
    CRLF + b"  // \xe2\x80\x94 LLM-driven title generation (step7) \xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94" + CRLF +
    b"  var stepLLM = require('./stepLLM');" + CRLF +
    b"  var s11 = ctx.deps[11] ? ctx.deps[11].data : null;" + CRLF +
    b"  var violations = (s11 ? (s11.violations || []) : []).filter(function(v) { return v.severity && v.severity !== 'none'; });" + CRLF +
    b"  var s5primary = (s5.primary || []).map(function(k) { return typeof k === 'string' ? k : (k.keyword || ''); }).filter(function(k) { return k; });" + CRLF +
    b"  log('  [step7] generating optimized titles via LLM...');" + CRLF +
    b"  var llmTitles = null;" + CRLF +
    b"  try {" + CRLF +
    b"    llmTitles = await stepLLM.generateOptimizedTitles({" + CRLF +
    b"      title: s2.title || ''," + CRLF +
    b"      brand: brand," + CRLF +
    b"      coreProduct: coreProduct," + CRLF +
    b"      primaryKeywords: s5primary," + CRLF +
    b"      violations: violations" + CRLF +
    b"    });" + CRLF +
    b"  } catch(e) {" + CRLF +
    b"    log('  [step7] LLM title gen failed: ' + e.message + ' \xe2\x80\x94 falling back to rule engine');" + CRLF +
    b"  }" + CRLF +
    b"  var versionA, versionB, versionC, recommendation;" + CRLF +
    b"  if (llmTitles && llmTitles.versionA && llmTitles.versionA.text) {" + CRLF +
    b"    versionA = llmTitles.versionA.text.substring(0, 200);" + CRLF +
    b"    versionB = llmTitles.versionB && llmTitles.versionB.text ? llmTitles.versionB.text.substring(0, 200) : versionA;" + CRLF +
    b"    versionC = llmTitles.versionC && llmTitles.versionC.text ? llmTitles.versionC.text.substring(0, 200) : versionB;" + CRLF +
    b"    recommendation = (llmTitles.versionA.note || 'Generated by LLM.') + ' Original char count: ' + (s2.title || '').length + '.';" + CRLF +
    b"    return {" + CRLF +
    b"      versionA: versionA," + CRLF +
    b"      versionB: versionB," + CRLF +
    b"      versionC: versionC," + CRLF +
    b"      topSegments: []," + CRLF +
    b"      recommendation: recommendation" + CRLF +
    b"    };" + CRLF +
    b"  }" + CRLF +
    b"  // Fallback: Rule-based title generation" + CRLF +
    b"  var CAPACITY_SIGNALS = /\\d+\\s*(lbs?|kg|oz|pcs?|piece|set|gal|hour|min|inch|cm|mm|ft)/i;"
)

idx7 = data.find(old7)
if idx7 < 0:
    print('step7 patch: NOT FOUND')
    sys.exit(1)
print('step7 patch: found at byte', idx7)
data = data[:idx7] + new7 + data[idx7+len(old7):]

# ── PATCH 2: step9 — insert LLM bullet generation before template engine ──
old9 = (
    CRLF + b"  var violations = s11 ? (s11.violations || []) : [];" + CRLF +
    b'  var missingEgeo = s12 ? (s12.egeoFeatures || []).filter(function(f) { return f.missing; }) : [];' + CRLF +
    CRLF + CRLF +
    b'  var violatedBullets = {};' + CRLF +
    b'  violations.forEach(function(v) {' + CRLF +
    b'    if (v.bullet) violatedBullets[v.bullet - 1] = v;' + CRLF +
    b'  });' + CRLF +
    CRLF + CRLF +
    b'  var optimized = bullets.map(function(bulletText, i) {' + CRLF +
    b'    var violationActions = [];' + CRLF +
    b'    var enhanceActions = [];' + CRLF +
    b'    var text = bulletText;'
)
new9 = (
    CRLF + b"  var violations = (s11 ? (s11.violations || []) : []).filter(function(v) { return v.severity && v.severity !== 'none'; });" + CRLF +
    b'  var missingEgeo = s12 ? (s12.egeoFeatures || []).filter(function(f) { return f.missing; }) : [];' + CRLF +
    CRLF +
    b"  // \xe2\x80\x94 LLM-driven bullet generation (step9) \xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94\xe2\x80\x94" + CRLF +
    b"  var stepLLM = require('./stepLLM');" + CRLF +
    b"  log('  [step9] generating optimized bullets via LLM...');" + CRLF +
    b"  var llmBullets = null;" + CRLF +
    b"  try {" + CRLF +
    b"    llmBullets = await stepLLM.generateOptimizedBullets({" + CRLF +
    b"      bullets: bullets," + CRLF +
    b"      violations: violations," + CRLF +
    b"      implicitViolations: s11 ? (s11.implicitViolations || []) : []," + CRLF +
    b"      missingEgeo: missingEgeo" + CRLF +
    b"    });" + CRLF +
    b"  } catch(e) {" + CRLF +
    b"    log('  [step9] LLM bullet gen failed: ' + e.message + ' \xe2\x80\x94 falling back to template');" + CRLF +
    b"  }" + CRLF +
    b"  if (llmBullets && llmBullets.bullets && llmBullets.bullets.length > 0) {" + CRLF +
    b"    var bulletMap = {};" + CRLF +
    b"    llmBullets.bullets.forEach(function(b) {" + CRLF +
    b"      if (b.index !== undefined) bulletMap[b.index - 1] = b;" + CRLF +
    b"    });" + CRLF +
    b"    var optimized = bullets.map(function(bulletText, i) {" + CRLF +
    b"      if (bulletMap[i]) {" + CRLF +
    b"        var b = bulletMap[i];" + CRLF +
    b"        var parts = [b.rewritten || bulletText];" + CRLF +
    b"        if (b.actions && b.actions.length > 0) {" + CRLF +
    b"          b.actions.forEach(function(a) { parts.push('  \xe2\x86\x92 ' + a); });" + CRLF +
    b"        }" + CRLF +
    b"        return parts.join('\\n');" + CRLF +
    b"      }" + CRLF +
    b"      return bulletText;" + CRLF +
    b"    });" + CRLF +
    b"    return { optimized: optimized, missingEgeo: missingEgeo.map(function(f) { return f.label; }), method: 'llm' };" + CRLF +
    b"  }" + CRLF +
    b"  // Fallback: Template-based bullet optimization" + CRLF +
    b"  var violatedBullets = {};" + CRLF +
    b"  violations.forEach(function(v) {" + CRLF +
    b"    if (v.bullet) violatedBullets[v.bullet - 1] = v;" + CRLF +
    b"  });" + CRLF +
    CRLF +
    b"  var optimized = bullets.map(function(bulletText, i) {" + CRLF +
    b"    var violationActions = [];" + CRLF +
    b"    var enhanceActions = [];" + CRLF +
    b"    var text = bulletText;"
)

idx9 = data.find(old9)
if idx9 < 0:
    print('step9 patch: NOT FOUND')
    sys.exit(1)
print('step9 patch: found at byte', idx9)
data = data[:idx9] + new9 + data[idx9+len(old9):]

with open(path, 'wb') as f:
    f.write(data)
print('Both patches applied. New size:', len(data))
